### ISSUE TITLE
Проблема с публикацией в Интернет

### ISSUE THREAD

**Issue by DotBlackDot** [MicrosoftDocs/powerbi-docs.ru-ru#10]
Ранее (до 01/01/2020) на бесплатной версии отчеты спокойно публиковались в интернет, сейчас не дает. Внедрение - Опубликовать в интернете, выскакивает окно - "Попросите администратора включить создание кодов внедрения". Ранее созданные отчеты работают. Аккаунт free, администратор я сам. При выборе вкладки "управление кодами внедрения" - нет никаких доступных параметров для новых отчетов.

---
#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта docs.microsoft.com с вопросом на GitHub.*

* ID: bc005634-24c6-15c4-4352-e1455d63f4f3
* Version Independent ID: 577c460a-08cc-892e-c5f9-e6106958f856
* Content: [Публикация в Интернете из Power BI - Power BI](https://docs.microsoft.com/ru-ru/power-bi/service-publish-to-web#feedback)
* Content Source: [powerbi-docs/service-publish-to-web.md](https://github.com/MicrosoftDocs/powerbi-docs.ru-ru/blob/live/powerbi-docs/service-publish-to-web.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @rkarlin
* Microsoft Alias: **rkarlin**

**Comment by srvbpigh** [comment]
Hello, @DotBlackDot
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by srvbpigh** [comment]
Здравствуйте, @DotBlackDot!  

Благодарим Вас за участие. Ваш отзыв связан с исходной документацией.  

Поэтому мы переносим Вашу заявку в репозиторий по английскому языку. Ее состояние можно просмотреть здесь: https://github.com/MicrosoftDocs/powerbi-docs/issues/1813.  

Мы очень ценим Ваш вклад в наши статьи.   

С наилучшими пожеланиями,  
Международная команда поддержки документации Майкрософт
