### ISSUE TITLE
function name translated

### ISSUE THREAD

**Issue by chizhova** [MicrosoftDocs/powerbi-docs.ru-ru#12]
Hi. On this page in some part of the DAX function samples the function names are translated to local language, which is incorrect. For example (russian):
we have: Продажи за прошлый квартал = ВЫЧИСЛИТЬ(СУММ(Sales[SalesAmount]) ПРЕДКВАРТАЛ(Calendar[DateKey]))
we need to have: Продажи за прошлый квартал = CALCULATE(SUM(Sales[SalesAmount]) PREVIOUSQUARTER(Calendar[DateKey]))

---
#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта docs.microsoft.com с вопросом на GitHub.*

* ID: e9d4e9e4-6581-ff12-0692-304725702fd3
* Version Independent ID: da0c52bf-88cc-367a-7475-039b785188a6
* Content: [Основные сведения о DAX в Power BI Desktop - Power BI](https://docs.microsoft.com/ru-ru/power-bi/desktop-quickstart-learn-dax-basics)
* Content Source: [powerbi-docs/desktop-quickstart-learn-dax-basics.md](https://github.com/MicrosoftDocs/powerbi-docs.ru-ru/blob/live/powerbi-docs/desktop-quickstart-learn-dax-basics.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by srvbpigh** [comment]
Hello, @chizhova
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by V-vafune** [comment]
Hello, @chizhova ,  

Thank you for your feedback. 

Our linguistic team reviewed your linguist suggestions and accepted them. We implemented your feedback and published to the updated articles on the Docs site to the following pages https://docs.microsoft.com/ru-ru/power-bi/desktop-quickstart-learn-dax-basics  

We truly appreciate your contribution to our articles and we encourage you to continue providing your valuable feedback. 

Kind regards, 
Microsoft DOCS International Team

**Comment by srvbpigh** [comment]
Здравствуйте, @chizhova!   

Спасибо за отзыв.  

Наши лингвисты рассмотрели Ваши предложения и приняли их. Мы внедрили Ваши правки в обновленные статьи на сайте документации, опубликованные на следующих страницах: https://docs.microsoft.com/ru-ru/power-bi/desktop-quickstart-learn-dax-basics.   

Мы очень ценим Ваш вклад в наши статьи и будем рады получить другие полезные отзывы.  

С наилучшими пожеланиями,  
Международная команда поддержки документации Майкрософт
