### ISSUE TITLE
Проблема просмотра опубликованного отчета

### ISSUE THREAD

**Issue by ProstoJohn** [MicrosoftDocs/powerbi-docs.ru-ru#14]
После успешной публикации отчета и попытке просмотреть его по ссылке которую выдал Power BI, возникает следущая ошибка: "Это содержимое недоступно. Дополнительные сведения о Power BI" (https://snipboard.io/fjmUAI.jpg), по ссылке "Дополнительные сведения о Power BI" (https://go.microsoft.com/fwlink/?LinkID=722383&clcid=0x409) никакой полезной информации не нашел. 

Как можно выйти из сложившейся ситуации? Заранее благодарю.

---
#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта docs.microsoft.com с вопросом на GitHub.*

* ID: bc005634-24c6-15c4-4352-e1455d63f4f3
* Version Independent ID: 577c460a-08cc-892e-c5f9-e6106958f856
* Content: [Публикация в Интернете из Power BI - Power BI](https://docs.microsoft.com/ru-ru/power-bi/service-publish-to-web#feedback)
* Content Source: [powerbi-docs/service-publish-to-web.md](https://github.com/MicrosoftDocs/powerbi-docs.ru-ru/blob/live/powerbi-docs/service-publish-to-web.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by srvbpigh** [comment]
Hello, @ProstoJohn
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Здравствуйте, @ProstoJohn 

Благодарим Вас за участие. Ваш отзыв связан с исходной документацией.  

Поэтому мы переносим Вашу заявку в репозиторий по английскому языку. Ее состояние можно просмотреть здесь:  https://github.com/MicrosoftDocs/powerbi-docs/issues/2152

Мы очень ценим Ваш вклад в наши статьи.   

С наилучшими пожеланиями,  

Международная команда поддержки документации Майкрософт
