### ISSUE TITLE
I have no tile button

### ISSUE THREAD

**Issue by dimaty26** [MicrosoftDocs/powerbi-docs.ru-ru#2]
I don't know why but I cannot add image/gif/video to my Dashboard due to missing "tile add" button. What can we do with that?

---
#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта docs.microsoft.com с вопросом на GitHub.*

* ID: 88b71635-b53c-d810-b40a-8c67ae1edba0
* Version Independent ID: 8de35da5-401a-7834-11de-7f4e8af35ca9
* Content: [Общие сведения о плитках панели мониторинга для разработчиков Power BI - Power BI](https://docs.microsoft.com/ru-ru/power-bi/service-dashboard-tiles#feedback)
* Content Source: [powerbi-docs/service-dashboard-tiles.md](https://github.com/MicrosoftDocs/powerbi-docs.ru-ru/blob/live/powerbi-docs/service-dashboard-tiles.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by CeciAc** [comment]
Hello, @dimaty26 

Your contribution is much appreciated. Our team can only answer feedback related to the documentation.
Please kindly log your product feedback by using the button "Give Product Feedback" at the bottom of the DOCS page.

If you have any feedback related to the documentation, please feel free to log it through this channel.
We truly appreciate your contribution to our articles. 
	
Kind regards,
Microsoft DOCS International Team
