### ISSUE TITLE
Wrong russian translation

### ISSUE THREAD

**Issue by chizhova** [MicrosoftDocs/powerbi-docs.ru-ru#3]
https://docs.microsoft.com/ru-ru/power-bi/power-bi-custom-visuals-certified?#getting-a-custom-visualcertified
"No watermarks are allowed". In russian it is translated incorrectly, it should be "водяные знаки не разрешены" \ "водяные знаки запрещены". As now, the meaning is hard to understand correctly.

---
#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта docs.microsoft.com с вопросом на GitHub.*

* ID: 43339087-a0a1-451d-76f6-bb6bad776a43
* Version Independent ID: 2ef46a24-2aeb-fbe3-821a-bffed8a03de0
* Content: [Сертифицированные пользовательские визуальные элементы Power BI - Power BI](https://docs.microsoft.com/ru-ru/power-bi/power-bi-custom-visuals-certified#feedback)
* Content Source: [powerbi-docs/power-bi-custom-visuals-certified.md](https://github.com/MicrosoftDocs/powerbi-docs.ru-ru/blob/live/powerbi-docs/power-bi-custom-visuals-certified.md)
* Service: **powerbi**
* Sub-service: **powerbi-custom-visuals**
* GitHub Login: @sranins
* Microsoft Alias: **rasala**

**Comment by CeciAc** [comment]
Hello, @chizhova
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by lichasu** [comment]
Здравствуйте, @chizhova !  
Спасибо за отзыв. 
Наши лингвисты рассмотрели Ваши предложения и приняли их. 
Мы очень ценим Ваш вклад в наши статьи и будем рады получить другие полезные отзывы. 
С наилучшими пожеланиями, 
Международная команда поддержки документации Майкрософт
