### ISSUE TITLE
Ошибки

### ISSUE THREAD

**Issue by MarchukNic** [MicrosoftDocs/powerbi-docs.ru-ru#4]
1) По данной инструкции не работает код, после шага редактирования исходного файла visual.ts
Запустить не удалось.

2) "В области обозревателя разверните папку src и выберите файл settings.ts." - не тот файл указан, должно быть "visual.ts".

---
#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта docs.microsoft.com с вопросом на GitHub.*

* ID: 5c4bae6e-72e1-e41c-4419-48a56423e81e
* Version Independent ID: 6d864495-b578-2d28-169d-edb5409de943
* Content: [Разработка визуального элемента Power BI - Power BI](https://docs.microsoft.com/ru-ru/power-bi/developer/custom-visual-develop-tutorial#feedback)
* Content Source: [powerbi-docs/developer/custom-visual-develop-tutorial.md](https://github.com/MicrosoftDocs/powerbi-docs.ru-ru/blob/live/powerbi-docs/developer/custom-visual-develop-tutorial.md)
* Service: **powerbi**
* Sub-service: **powerbi-custom-visuals**
* GitHub Login: @sranins
* Microsoft Alias: **rasala**

**Comment by srvbpigh** [comment]
Hello, @MarchukNic
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Здравствуйте, @MarchukNic
Благодарим Вас за участие. Ваш отзыв связан с исходной документацией. 
Поэтому мы переносим Вашу заявку в репозиторий по английскому языку. Ее состояние можно просмотреть здесь: https://github.com/MicrosoftDocs/powerbi-docs/issues/1337
Мы очень ценим Ваш вклад в наши статьи.  
С наилучшими пожеланиями, 
Международная команда поддержки документации Майкрософт

**Comment by zBritva** [comment]
@MarchukNic hello, could you confirm or reject that issues is actual for you? If it actual, could you share detials, what do you do and what happens with the visual compiling (screenshoots, error messanges)?

Добрый день! Если для Вас проблема все еще актуальна, не могли бы  рассказать детали? Что вы выполняете и какая ошибка возникает (скриншоты или сообщения об ошибке)?

Спасибо!
