### ISSUE TITLE
в запросах есть ожидающие изменения

### ISSUE THREAD

**Issue by kum12neon** [MicrosoftDocs/powerbi-docs.ru-ru#7]
где кнопка "ОТМЕНИТЬ" ???

---
#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта docs.microsoft.com с вопросом на GitHub.*

* ID: bb95c243-439b-5f81-51ae-c28efa0d22c3
* Version Independent ID: 7e0c5adf-c752-4ebf-5022-e3bd64f3f8d3
* Content: [Источники данных для Power BI - Power BI](https://docs.microsoft.com/ru-ru/power-bi/service-get-data#feedback)
* Content Source: [powerbi-docs/service-get-data.md](https://github.com/MicrosoftDocs/powerbi-docs.ru-ru/blob/live/powerbi-docs/service-get-data.md)
* Service: **powerbi**
* Sub-service: **powerbi-service**
* GitHub Login: @davidiseminger
* Microsoft Alias: **davidi**

**Comment by srvbpigh** [comment]
Hello, @kum12neon
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by kum12neon** [comment]
"there are pending changes in requests, ..."
where is the "CANCEL" button ???

**Comment by CeciAc** [comment]
Здравствуйте, @kum12neon
Благодарим Вас за предоставленный комментарий. Комментарии помогают нам постоянно улучшать портал docs.microsoft.com. Однако нам необходимы дополнительные сведения, чтобы проанализировать Ваш отзыв. Не могли бы Вы дать более подробную информацию и пояснить свой комментарий?
С уважением,
Международная команда Microsoft DOCS

**Comment by kum12neon** [comment]
Здравствуйте CeciAc !

Проясню ситуацию. Сама програма еще достаточно "сырая" и максимально запутана в Названиях "полей". Если сравнить например механику сопоставления Гугл-Аналитики и BI то тут можна потратить уйму времени на то, чтобы найти подходящие (нужные) поля для моего отчета из Аналитики в самом BI. Т.е. - они сильно различаются как самим названием так и категорией (по структуре дерева категорий).

Потому, когда BI попросил "Принять" изменения без возможности их "Отменить", у меня и возник этот вопрос - почему нет кнопки "отката" к преыдущему состоянию набора команд формирования запроса в Аналитику гугла (и в остальные базы данных - также) ?

**Comment by CeciAc** [comment]
Здравствуйте, @kum12neon
Благодарим Вас за участие. Ваш отзыв связан с исходной документацией. 
Поэтому мы переносим Вашу заявку в репозиторий по английскому языку. Ее состояние можно просмотреть здесь: https://github.com/MicrosoftDocs/powerbi-docs/issues/1625

Мы очень ценим Ваш вклад в наши статьи.  
С наилучшими пожеланиями, 
Международная команда поддержки документации Майкрософт
