### ISSUE TITLE
Лицензирование Power BI

### ISSUE THREAD

**Issue by TimTacko** [MicrosoftDocs/powerbi-docs.ru-ru#8]
На странице, в строке "Лицензия" указано, что для продукта "Сервер отчетов Power BI" необходим SQL Server ЕЕ с правами системного администратора. Полагаю, что тут имеет место ошибка перевода, вместо системного администратора необходимо указать Software Assurance.

---
#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта docs.microsoft.com с вопросом на GitHub.*

* ID: a5e43027-f0e6-928a-8c16-4401ee8d0e52
* Version Independent ID: 51c87d50-4316-c0d9-a31c-3163d1557e1f
* Content: [Сравнение решения ](https://docs.microsoft.com/ru-ru/power-bi/report-server/compare-report-server-service#feedback)
* Content Source: [powerbi-docs/report-server/compare-report-server-service.md](https://github.com/MicrosoftDocs/powerbi-docs.ru-ru/blob/live/powerbi-docs/report-server/compare-report-server-service.md)
* Service: **powerbi**
* Sub-service: **powerbi-report-server**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by srvbpigh** [comment]
Hello, @TimTacko
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Здравствуйте, @TimTacko 
Благодарим Вас за участие. Ваш отзыв связан с исходной документацией. 
Поэтому мы переносим Вашу заявку в репозиторий по английскому языку. Ее состояние можно просмотреть здесь: https://github.com/MicrosoftDocs/powerbi-docs/issues/1608
Мы очень ценим Ваш вклад в наши статьи.  
С наилучшими пожеланиями, 
Международная команда поддержки документации Майкрософт
